spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice-demo?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: openning
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
